SOURCE create_tables.sql;

LOAD DATA LOCAL INFILE 'kapitels.csv' INTO TABLE `ddd_test`.`kapitels` FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'themas.csv' INTO TABLE `ddd_test`.`themas` FIELDS TERMINATED BY '$' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'users.csv' INTO TABLE `ddd_test`.`users` FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'vocab.csv' INTO TABLE `ddd_test`.`vocab` FIELDS TERMINATED BY '$' LINES TERMINATED BY '\n';
